#!/usr/bin/env python

import os
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("files", nargs='+')
args = parser.parse_args()

for file in args.files:
    print(os.path.abspath(file))
