#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys

for line in sys.stdin:
  if '▁' in line:
    print(line.replace(' ', '').replace('▁', ' ').strip(), flush=True)
  else:
    print(line.replace('@@ ', '').replace('@@', ''), flush=True)
