#!/usr/bin/env python3

"""
Tab-preserving tokenizer built on Sacremoses.
"""

import sys
import argparse

from sacremoses import MosesDetokenizer


parser = argparse.ArgumentParser("Tab-preserving detokenizer.")
parser.add_argument("--lang", "-l", default="en")
args = parser.parse_args()

detok = MosesDetokenizer(lang=args.lang)

for line in sys.stdin:
    fields = [detok.detokenize(field.split()) for field in line.rstrip().split("\t")]
    print(*fields, sep="\t")
