#!/usr/bin/env python3

# Silly convenience function for returning
# source/target of a dashed pair.
#
# $ echo en-de | getpair src
# en


import sys

def main(args):
    for line in sys.stdin:
        line = line.strip()
        src, trg = line.split("-")
        vals = { "src": src,
                 "trg": trg,
                 "sorted": args.join.join(sorted([src,trg]))
             }

        output = [vals[x] for x in args.output]
        print(args.join.join(output))

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("output", nargs="*", default=["sorted"])
    parser.add_argument("--join", "-j", default="-")
    args = parser.parse_args()
    main(args)
