#!/usr/bin/env python

"""
Converts among language names and abbreviations using Python's ISO-639 module.
"""

import sys
import iso639

if len(sys.argv) != 2:
   print "Usage: iso639 LANG"
   print "where LANG is a language name or abbreviation."
   sys.exit(1)

input = sys.argv[1]

if len(input) == 2:
   lang = iso639.languages.get(part1 = input)
   print lang.name
elif len(input) == 3:
   lang = iso639.languages.get(part3 = input)
   print lang.name
else:
   lang = iso639.languages.get(name = input)
   print lang.part1
