#!/usr/bin/perl -w

use strict;

my $logfile = "./.philog.LOGFILE";

my $date = `date`; chop($date);
my $pwd = `pwd`; chop($pwd);
my $pretty = 0; 
my $curdir = 0;
my $clean = 0;
my $history = 0;
foreach (@ARGV) {
	$pretty = 1 if /^-pretty$/;
	$curdir = 1 if /^-dir$/;
	$clean = 1 if /^-clean$/;
	$history = 1 if /^-history$/;
}

if ($history) {
  my @cmd = <STDIN>;
  my $last = 1;
  $last = $ARGV[1] if $#ARGV>0 && $ARGV[1] =~ /^\d+$/;
  my $cmd =  $cmd[$#cmd-$last];
  $cmd =~ s/^\s*\d+\s*//;
  $cmd =~ s/^[\d\-]+ [\d\:]+\s*//;
  chomp($cmd);
  &log($cmd);
}
elsif ($#ARGV-$pretty-$clean == -1) {
	open(LOG,$logfile);
	while(<LOG>) {
		/^(... ... .. ..:..:.. ..T 20..) (\S+) (.+)$/;
		my ($time,$dir,$cmd) = ($1,$2,$3);
		if($pretty) {
	    print "\e[32m$time \e[34m$dir ".($cmd=~/^[\#\^]/?"\e[30;1m":"\e[m").$cmd."\e[m\n";
		}
		elsif ($clean) {
	    print "$cmd\n";
		}
		else {
	    print "$time $dir $cmd\n";
		}
	}
	close(LOG);	
}
elsif ($curdir) {
	open(LOG,$logfile);
	while(<LOG>) {
		/^(... ... .. ..:..:.. ..T 20..) (\S+) (.+)$/;
		my ($time,$dir,$cmd) = ($1,$2,$3);
		next unless &same_dir($dir,$pwd);
		if ($pretty) {
	    print "\e[32m$time ".($cmd=~/^[\#\^]/?"\e[30;1m":"\e[m").$cmd."\e[m\n";
		}
		elsif ($clean) {
	    print "$cmd\n";
		}
		else {
	    print "$1 $3\n";
		}
	}
	close(LOG);
}
else {
	my $cmd;
	foreach (@ARGV) { $cmd .= "$_ "; }
	chop($cmd);
	&log($cmd);
}

sub log {
	my ($cmd) = @_;
	open(LOG,">>$logfile");
	print LOG "$date $pwd $cmd\n";
	close(LOG);
}

sub same_dir {
	my ($a,$b) = @_;
	$a =~ s/nfs\/[^\/]+/nfs/;
	$b =~ s/nfs\/[^\/]+/nfs/;
	return $a eq $b;
}
