#!/usr/bin/env python3

"""
Reservoir sampler in Python. Selects k items uniformly at random from an arbitrary-length stream.
"""

import argparse
import random
import sys

def main(args):

    samples = []

    for i, line in enumerate(sys.stdin, 1):

        line = line.rstrip()

        if len(samples) < args.num_samples:
            samples.append(line)
        else:
            # Accept new element from the stream with probability num_samples / i,
            # and replace a random element of the sample with it.
            if random.random() < 1. * args.num_samples / i:
                where = random.randint(0, args.num_samples - 1)
                samples[where] = line

    print('\n'.join(samples))

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--seed', type=int, default=None)
    parser.add_argument('num_samples', type=int, nargs='?', default=10)
    args = parser.parse_args()

    random.seed(args.seed)

    main(args)
