#!/usr/bin/env python

import random

def roll(num = 1):
  return [random.choice([u'\u2680', u'\u2681', u'\u2682', u'\u2683', u'\u2684', u'\u2685']) for x in range(num)]

if __name__ == '__main__':
  import argparse
  arg_parser = argparse.ArgumentParser()
  arg_parser.add_argument('-n', default=1, type=int, help='number of dice to roll')
  arg_parser.add_argument('-t', default=1, type=int, help='number of times to roll N dice')
  args = arg_parser.parse_args()

  if args.t >= 1:
    for num in range(args.t):
      print ' '.join(roll(args.n))
