#!/usr/bin/python3

import re
import sys
import argparse

parser = argparse.ArgumentParser(description='Sum numbers in a column of text')
parser.add_argument('col', nargs='?', type=int, default=-1, help='Which column? (0-indexed)')
parser.add_argument('-p', dest='pretty', default=False, action='store_true', help='Pretty-print')
parser.add_argument('-b', dest='bytes', default=False, action='store_true', help='Summarize')
parser.add_argument('-v', dest='verbose', default=False, action='store_true', help='Verbose')
args = parser.parse_args()

total = 0
line_count = 0
for line in sys.stdin:
    line_count += 1
    tokens = re.split(r'\s+', line.rstrip())
    total += float(tokens[args.col])

sum = total
if args.verbose:
    print("%s (%d lines)" % (sum, line_count))
else:
    print(sum)
