#!/usr/bin/env python3

import argparse
import re

parser = argparse.ArgumentParser()
parser.add_argument("--collapse", "-c", action="store_true", help="Also collapse multiple whitespaces into one")
parser.add_argument("--punc", "-p", action="store_true", help="Remove punctuation")
args = parser.parse_args()

import sys
for line in sys.stdin:
    line = line.strip()

    if args.collapse:
        line = re.sub(r" +", " ", line)

    if args.punc:
        line = "".join(c for c in line if c.isalnum() or c.isspace())

    print(line, flush=True)
